<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>${groupId}</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>${version}</version>

  <properties>
    <bpm-testing.version>1.0.1-SNAPSHOT</bpm-testing.version>
    <project.build.sourceEncoding>ISO-8859-1</project.build.sourceEncoding>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <!-- sonar properties -->
    <sonar.host.url>http://localhost:8080</sonar.host.url>
    <!-- add more paths below to point to external scripts -->
    <sonar.sources>sonar/generated/scripts,bpmn/scripts</sonar.sources>
    <sonar.inclusions>**/*.groovy,**/*.js</sonar.inclusions>
    <sonar.lang.patterns.grvy>**/*.groovy</sonar.lang.patterns.grvy>
    <sonar.coverageReportPaths>target/coverage-collection/sonar/coverage.xml</sonar.coverageReportPaths>
    <resourcesPath>.</resourcesPath>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.finos.fluxnova.bpm.test</groupId>
        <artifactId>fluxnova-bpm-testing-bom</artifactId>
        <version>${bpm-testing.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.finos.fluxnova.bpm.test</groupId>
      <artifactId>fluxnova-bpm-testing</artifactId>
      <version>${bpm-testing.version}</version>
    </dependency>
    <dependency>
      <groupId>org.finos.fluxnova.bpm.test</groupId>
      <artifactId>fluxnova-bpm-testing-mockito</artifactId>
      <version>${bpm-testing.version}</version>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.wiremock</groupId>
      <artifactId>wiremock-standalone</artifactId>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.finos.fluxnova.bpm.test</groupId>
      <artifactId>fluxnova-bpm-testing-process-coverage</artifactId>
      <version>${bpm-testing.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.6.0</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.gmavenplus</groupId>
          <artifactId>gmavenplus-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.0.2</version>
        <configuration>
          <outputDirectory>${project.build.directory}/test-classes</outputDirectory>
          <resources>
            <resource>
              <directory>src/main/resources</directory>
              <includes>
                <include>**/*.bpmn</include>
                <include>**/*.js</include>
                <include>**/*.groovy</include>
                <include>**/*.dmn</include>
              </includes>
            </resource>
            <resource>
              <directory>src/test/resources</directory>
              <includes>
                <include>**/*</include>
              </includes>
            </resource>
            <resource>
              <directory>${resourcesPath}</directory>
              <includes>
                <include>**/*.bpmn</include>
                <include>**/*.js</include>
                <include>**/*.groovy</include>
                <include>**/*.dmn</include>
                <include>**/__files</include>
                <include>**/db</include>
              </includes>
              <excludes>
                <exclude>**/target/**</exclude>
                <exclude>**/src/test/resources/**</exclude>
              </excludes>
            </resource>
          </resources>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <configuration>
          <testSources>
            <testSource>
              <directory>${project.basedir}/src/test/groovy</directory>
              <includes>
                <include>**/*.groovy</include>
              </includes>
            </testSource>
          </testSources>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compileTests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <includes>
            <include>**/*test*.class</include>
            <include>**/*Test*.class</include>
          </includes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.finos.fluxnova.bpm.test</groupId>
        <artifactId>fluxnova-bpm-coverage-collection-plugin</artifactId>
        <version>${bpm-testing.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>collect-coverage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
