name: "Build Testing framework and Deploy"

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-default-branch-{0}-{1}', github.sha, github.workflow) ||
    format('ci-pr-{0}-{1}', github.ref, github.workflow) }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  actions: read
  pull-requests: write
  attestations: write
  id-token: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.version.outputs.image_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Java setup
        uses: ./.github/actions/java-setup

      - name: Configure git
        uses: ./.github/actions/configure-git

      - name: Download deps and plugins
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -s ./settings.xml

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build & Deploy
        uses: ./.github/actions/build-deploy
        with:
          branch: ${{ github.ref_name }}

      - name: Tests
        env:
          MAVEN_OPTS: "-Xmx8g"
        shell: bash
        run: |
          mvn -B -e -U verify
